name: Deploy

on:
  push:
    branches:
    - development

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Build & deploy
      uses: JamesIves/github-pages-deploy-action@v2.0.3
      env:
        ACCESS_TOKEN: ${{ secrets.SSH_PRIVATE_KEY }}
        BASE_BRANCH: development
        BRANCH: master
        FOLDER: dist
        BUILD_SCRIPT: yarn install && yarn build
