name: Deploy

on:
  push:
    branches:
    - development

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: webfactory/ssh-agent@v0.1.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Install dependencies
      run: yarn install
    - name: Run ESLint
      run: yarn eslint
    - name: Run stylelint
      run: yarn stylelint
    - name: Deploy
      run: |
        yarn build
        yarn deploy
